In [2]:
# function to encrypt a data file

keyfile='datafiles/key.txt'

def dictionarykeyfile(keyfile):
    key={}
    with open(keyfile,'r') as f:
        for line in f:
            line=line.split()
            key[line[0]] = line[1]
    return key

dictionarykeyfile(keyfile)        

def encryptmarksdata(datafile,keyfile):
    
    key = dictionarykeyfile(keyfile)
    
    with open(datafile,'r') as f:
        
        filedata = f.read().split('\n')
        
    with open('datafiles/encryptedmarks.txt','w') as f:
        
        for mark in filedata:
            
            line = ' '
            
            for n in mark:
                
                line += key[n]
                
            f.write(line+'\n')
    return

datafile = 'datafiles/marks.txt'

encryptmarksdata(datafile,keyfile)

                
                
                
        
        


#constructing a dictionary for key data



In [3]:
# Comprehensions

keyfile = 'datafiles/key.txt'

key=dictionarykeyfile(keyfile)

key



{'0': '4',
 '1': '5',
 '2': '6',
 '3': '7',
 '4': '8',
 '5': '9',
 '6': '0',
 '7': '1',
 '8': '2',
 '9': '3'}

In [5]:
# Comprehensions

keyfile = 'datafiles/key.txt'

key=dictionarykeyfile(keyfile)

evenkeys = {item for item in key.items() if int(item[0])%2 == 0}

evenkeys


{('0', '4'), ('2', '6'), ('4', '8'), ('6', '0'), ('8', '2')}

In [6]:
# Comprehensions

keyfile = 'datafiles/key.txt'

key=dictionarykeyfile(keyfile)

evenkeys = {item for item in key}

evenkeys


{'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'}

# Python Libraries

# Numpy Library

- to processing the n dimensional arrays

In [10]:
import numpy as np

li = [1,2,3]

a=np.array(li)

a

array([1, 2, 3])

In [11]:
import numpy as np

li = [1,2,3]

a=np.array(li)

type(a)

numpy.ndarray

In [12]:
import numpy as np

li = [1,2,3,'a']

a=np.array(li)
a

array(['1', '2', '3', 'a'], dtype='<U11')

In [13]:
import numpy as np

li = [1,2,3,'a']

a=np.array(li)

b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
# Generae of N Random Numbers using Numpy

rn=np.random.randint(0,100,size=10)
rn

array([81,  4, 92, 59, 77, 16, 69, 85, 88, 40])

In [20]:
# generate a three dimensional arrays using numpy

m3 = np.random.randint(0,2,size=(3,3))
m3

array([[1, 0, 1],
       [0, 0, 0],
       [1, 0, 1]])

In [25]:

m3 = np.random.randint(0,2,size=(3,3,3))
m3[0][2]
m3

array([[[1, 1, 1],
        [0, 1, 0],
        [1, 1, 1]],

       [[0, 1, 0],
        [0, 1, 0],
        [1, 0, 1]],

       [[1, 0, 1],
        [1, 0, 1],
        [0, 0, 1]]])

In [26]:

m3 = np.random.randint(0,2,size=(3,3,3,3))
m3[0][2]
m3

array([[[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 0]],

        [[1, 1, 1],
         [1, 0, 1],
         [1, 1, 0]],

        [[0, 1, 1],
         [1, 1, 0],
         [0, 1, 1]]],


       [[[0, 0, 1],
         [0, 0, 0],
         [1, 1, 0]],

        [[0, 1, 0],
         [1, 0, 1],
         [0, 0, 1]],

        [[0, 0, 0],
         [1, 0, 0],
         [1, 0, 0]]],


       [[[0, 1, 1],
         [0, 0, 1],
         [0, 0, 1]],

        [[1, 0, 1],
         [0, 1, 1],
         [1, 0, 1]],

        [[1, 0, 1],
         [1, 1, 1],
         [0, 1, 0]]]])

In [29]:

m3 = np.random.randint(0,2,size=(3,3,3,3))
m3[2][2][2][1]


1

In [34]:
m3.ndim


4

In [33]:
m3.size

81

In [35]:
m3.shape

(3, 3, 3, 3)

In [36]:
m3.dtype

dtype('int32')

In [37]:
m3.itemsize

4

In [38]:
m3.nbytes

324

In [39]:
m3.ndim
m3.size
m3.shape
m3.dtype
m3.itemsize
m3.nbytes


324

In [44]:
m3 = np.random.randint(0,2,size=(3,3))
m3m3 = np.random.randint(0,2,size=(3,3))
m3[::-1,::-1]

array([[1, 0, 0],
       [0, 1, 0],
       [0, 1, 0]])

In [45]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [46]:
b.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
b.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [54]:
import numpy as np

a=np.array([0,2,4])
b=np.array([0,2,4])
print("Matrix A\n",a)
print("Matrix B\n",b)
print("A+B\n",a+b)
print("Adding Elements for A To B:",5+a)

Matrix A
 [0 2 4]
Matrix B
 [0 2 4]
A+B
 [0 4 8]
Adding Elements for A To B: [5 7 9]


In [56]:
a = np.array([[1, 2], [3, 4]])
a


array([[1, 2],
       [3, 4]])

In [58]:
 a.transpose()


array([[1, 3],
       [2, 4]])

In [59]:
a = np.array([[1, 2,3], [3, 4,5],[9, 4,5]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [9, 4, 5]])

In [60]:
a.transpose()

array([[1, 3, 9],
       [2, 4, 4],
       [3, 5, 5]])

In [61]:

a = np.array([[1, 2,3], [3, 4,5],[9, 4,5]])
a


array([[1, 2, 3],
       [3, 4, 5],
       [9, 4, 5]])

In [62]:

b = np.array([[1, 2,3], [3, 4,5],[9, 4,5]])
b


array([[1, 2, 3],
       [3, 4, 5],
       [9, 4, 5]])

In [63]:
np.matmul(a,b)

array([[34, 22, 28],
       [60, 42, 54],
       [66, 54, 72]])

In [66]:
np.min(a)

1

In [67]:
np.max(a)

9

In [68]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [9, 4, 5]])

# Pandas

- IT IS FOR

USE CASES:
--------------------
# Data analysis 

# Data cleaning

# Data tranformation

# Notations

# 1.Series

# 2.Data frame

In [9]:
# example for pandas



import pandas as pd

internal1 = {'s1:':21,'s2:':18,'s3:':22}
internal1=pd.Series(internal1)

internal2={'s1:':1,'s2:':14,'s3:':29}
internal2=pd.Series(internal2)
internal2



s1:     1
s2:    14
s3:    29
dtype: int64

In [10]:
final={'internal1':internal1,'internal2':internal2}

final = pd.DataFrame(final)

final

internal1  internal2
s1:         21          1
s2:         18         14
s3:         22         29

In [11]:
final={'internal1':internal1,'internal2':internal2}

final = pd.DataFrame(final)

final['internal1']

s1:    21
s2:    18
s3:    22
Name: internal1, dtype: int64

In [12]:
final={'internal1':internal1,'internal2':internal2}

final = pd.DataFrame(final)

final['internal2']

s1:     1
s2:    14
s3:    29
Name: internal2, dtype: int64

In [13]:
final.columns #names of all columns

Index(['internal1', 'internal2'], dtype='object')

In [14]:
final.values # lists of all rows

array([[21,  1],
       [18, 14],
       [22, 29]], dtype=int64)

In [17]:
final.values[2]

array([22, 29], dtype=int64)

In [18]:
final.values[2,0]

22

In [19]:
final.values[2,1]

29

In [20]:
final.values[2][1]

29

In [27]:
for row in final.values:
    
    print('Internal1-',+row[0],'Internal2-',+row[1])

Internal1- 21 Internal2- 1
Internal1- 18 Internal2- 14
Internal1- 22 Internal2- 29


In [29]:
for row in final.values:
    
    print('Internal1-',+row[0])

Internal1- 21
Internal1- 18
Internal1- 22


In [28]:
for row in final.values:
    
    print('Internal2-',+row[1])

Internal2- 1
Internal2- 14
Internal2- 29


In [33]:
# add row
final.loc['s4']=[13,56]
final

internal1  internal2
s1:         21          1
s2:         18         14
s3:         22         29
3           13         56
s4          13         56

In [35]:
# del row

final.drop(3)

internal1  internal2
s1:         21          1
s2:         18         14
s3:         22         29
s4          13         56

In [37]:
final.values[2,0]=25
final

internal1  internal2
s1:         21          1
s2:         18         14
s3:         25         29
3           13         56
s4          13         56

In [39]:
final.values[1] = [14,18]
final

internal1  internal2
s1:         21          1
s2:         14         18
s3:         56         13
3           13         56
s4          13         56

In [40]:
final.drop(3)

internal1  internal2
s1:         21          1
s2:         14         18
s3:         56         13
s4          13         56

In [45]:
# Reading csv file Data
import pandas as pd
filepath = 'datafiles/income.csv'
incomedf = pd.read_csv(filepath)
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [47]:
# Extract Income of all states in 2013

incomedf.values[-1,-1]

57528

In [48]:
# Extract Income of all states in 2013

for row in incomedf.values:
    print(row[1],':',row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [51]:
# Average income of a particular state AriZola

sum=0
for i in range(2,11):
    sum += incomedf.values[2][i]
    
sum/len(incomedf.values[2][2:])




47214.77777777778